"""
ChatBI Application - LangGraph stateful workflow
------------------------------------------------
Node flow:
  resolve_query -> normalize -> retrieve_schema -> validate_schema -> generate_sql -> check_sql
       v (resolve references)                           v (empty schema)     ^                v (failed and retries < 2)
  (overwrites question)                               respond               +----------------+
                                                                                             v (success or retries >= 2)
                                                                                          respond
"""

import os
import sys

from colorama import Fore, Style
from langchain_core.messages import HumanMessage
from langchain_openai import ChatOpenAI
from langgraph.graph import StateGraph, END
from langgraph.checkpoint.memory import InMemorySaver
from typing_extensions import TypedDict

sys.path.insert(0, os.path.dirname(__file__))

from config import settings
from core.logger import audit, new_trace_id
from response import format_roles
from response.sql_builder import SQLBuilder
from db_mcp_server.entity_normalizer import EntityNormalizer
from db_mcp_server.query_normalizer import QueryNormalizer
from db_mcp_server.schema_rag import SchemaRAG
from db_mcp_server.utils import query as db_query


# ─────────────────────────────────────────────
# State definition
# ─────────────────────────────────────────────
class ChatBIState(TypedDict):
    question:         str
    resolved_question: str   # Question after resolve_query expands references; shown when changed
    normalized_query: str
    roles:            dict   # {metric, time, comparison, status, aggregation, limit, entity, location}
    schema_context:   dict   # {"tables": [...], "join_paths": [...]}
    generated_sql:    str    # Raw SQL generated by the LLM on the current attempt
    final_sql:        str    # SQL confirmed after check_sql succeeds
    result:           list
    error:            str
    retries:          int
    redirect_hint:    str    # Follow-up guidance shown to the user when non-empty
    history:          list   # Multi-turn history, each item is {"question": str, "roles": dict, "result_summary": str}


# ─────────────────────────────────────────────
# Component initialization
# ─────────────────────────────────────────────
llm              = ChatOpenAI(
    model=settings.llm.model,
    temperature=settings.llm.temperature,
    api_key=os.environ.get("OPENAI_API_KEY"),
)
normalizer       = EntityNormalizer()
query_normalizer = QueryNormalizer(llm, normalizer)
rag              = SchemaRAG(llm=llm)
builder          = SQLBuilder(llm)


_RESOLVE_PROMPT = """\
You are a conversational query resolution assistant. Use the dialogue history to rewrite
the user's new question as a complete, standalone query.
If the new question is already complete and does not depend on earlier context,
return it unchanged.
Output only the rewritten question, with no explanation and no quotation marks.

Dialogue history (most recent turns):
{history}

New user question: {question}
"""


# ─────────────────────────────────────────────
# Node definitions
# ─────────────────────────────────────────────
def resolve_query_node(state: ChatBIState) -> dict:
    """Resolve multi-turn references by expanding follow-up questions into standalone queries."""
    history = state.get("history", [])
    question = state["question"]
    if not history:
        return {"resolved_question": question}

    history_text = "\n".join(
        f"Q{i+1}: {h['question']} -> involved {_fmt_roles(h.get('roles', {}))}, returned {h['result_summary']}"
        for i, h in enumerate(history[-3:])
    )
    prompt = _RESOLVE_PROMPT.format(history=history_text, question=question)
    response = llm.invoke([HumanMessage(content=prompt)])
    resolved = response.content.strip().strip('"').strip("'")
    return {"resolved_question": resolved}


def _fmt_roles(roles: dict) -> str:
    parts = []
    for key in ("entity", "location", "metric", "time"):
        items = roles.get(key, [])
        if not items:
            continue
        if isinstance(items[0], dict):
            parts.append(", ".join(i.get("normalized", i.get("original", "")) for i in items))
        else:
            parts.append(", ".join(str(i) for i in items))
    return " / ".join(parts) if parts else "unknown"


def normalize_node(state: ChatBIState) -> dict:
    question = state.get("resolved_question") or state["question"]
    return query_normalizer.run(question)


def retrieve_schema_node(state: ChatBIState) -> dict:
    schema = rag.retrieve(state["normalized_query"])
    return {"schema_context": schema}


def validate_schema_node(state: ChatBIState) -> dict:
    """Layer 1 fallback: short-circuit to respond when the schema is empty."""
    tables = state.get("schema_context", {}).get("tables", [])
    if not tables:
        return {
            "redirect_hint": (
                "No relevant tables were retrieved. Please try rephrasing the question.\n"
                "Suggestions:\n"
                "  - Use more specific business terms such as brand, city, or order status.\n"
                "  - Avoid overly conversational phrasing.\n"
                "  - You can first ask 'Which brands/cities/categories are available?' "
                "to confirm queryable entities."
            )
        }
    return {}


def generate_sql_node(state: ChatBIState) -> dict:
    sql = builder.build(
        normalized_query=state["normalized_query"],
        schema_context=state["schema_context"],
        roles=state.get("roles", {}),
        error=state.get("error", ""),
        prev_sql=state.get("generated_sql", ""),
    )
    return {"generated_sql": sql, "error": ""}


def check_sql_node(state: ChatBIState) -> dict:
    try:
        result = db_query(state["generated_sql"])
        return {"result": result, "final_sql": state["generated_sql"], "error": ""}
    except Exception as e:
        return {"error": str(e), "retries": state.get("retries", 0) + 1}


def respond_node(state: ChatBIState) -> dict:
    updates: dict = {}

    # Layer 2 fallback: retries exhausted and still failing -> schema likely mismatched
    if state.get("retries", 0) >= 2 and state.get("error") and not state.get("redirect_hint"):
        updates["redirect_hint"] = (
            "SQL generation failed multiple times. The question may be too ambiguous or "
            "refer to data outside the current database scope.\n"
            "Suggestions:\n"
            "  - Split the question into smaller steps and check base data first.\n"
            "  - Specify constraints such as time range, region, or brand.\n"
            "  - Confirm entity names are correct, including brand spelling."
        )

    # Layer 3a fallback: SQL succeeded but returned no rows
    if not state.get("error") and len(state.get("result", [])) == 0 and not state.get("redirect_hint"):
        updates["redirect_hint"] = (
            "The query ran successfully but returned no data. Possible reasons:\n"
            "  - An entity name may be misspelled, such as a brand or city.\n"
            "  - There may be no records in the selected time range.\n"
            "  - The conditions may be too strict. Try removing some filters."
        )

    hint = updates.get("redirect_hint", state.get("redirect_hint", ""))
    audit({
        "question":         state["question"],
        "normalized_query": state["normalized_query"],
        "roles":            state.get("roles", {}),
        "final_sql":        state.get("final_sql", state.get("generated_sql", "")),
        "success":          not bool(state.get("error")),
        "retries":          state.get("retries", 0),
        "row_count":        len(state.get("result", [])),
        "error":            state.get("error", ""),
        "redirect_hint":    hint,
    })
    return updates


# ─────────────────────────────────────────────
# Conditional edges
# ─────────────────────────────────────────────
def schema_valid(state: ChatBIState) -> str:
    return "respond" if state.get("redirect_hint") else "generate_sql"


def should_retry(state: ChatBIState) -> str:
    if state.get("error") and state.get("retries", 0) < 2:
        return "generate_sql"
    return "respond"


# ─────────────────────────────────────────────
# Build the StateGraph
# ─────────────────────────────────────────────
def build_graph():
    graph = StateGraph(ChatBIState)
    graph.add_node("resolve_query",    resolve_query_node)
    graph.add_node("normalize",        normalize_node)
    graph.add_node("retrieve_schema",  retrieve_schema_node)
    graph.add_node("validate_schema",  validate_schema_node)
    graph.add_node("generate_sql",     generate_sql_node)
    graph.add_node("check_sql",        check_sql_node)
    graph.add_node("respond",          respond_node)

    graph.set_entry_point("resolve_query")
    graph.add_edge("resolve_query",   "normalize")
    graph.add_edge("normalize",       "retrieve_schema")
    graph.add_edge("retrieve_schema", "validate_schema")
    graph.add_conditional_edges("validate_schema", schema_valid, {
        "generate_sql": "generate_sql",
        "respond":      "respond",
    })
    graph.add_edge("generate_sql",    "check_sql")
    graph.add_conditional_edges("check_sql", should_retry, {
        "generate_sql": "generate_sql",
        "respond":      "respond",
    })
    graph.add_edge("respond", END)

    return graph.compile(checkpointer=InMemorySaver())


# ─────────────────────────────────────────────
# Main entry point
# ─────────────────────────────────────────────
def main():
    app     = build_graph()
    config  = {"configurable": {"thread_id": "1"}}
    history: list = []   # Cross-turn history, keep at most 5 items

    print(Fore.CYAN + Style.BRIGHT + "ChatBI Application (LangGraph StateGraph)")
    print("Enter a question to start querying, or type 'q' to quit.\n" + Style.RESET_ALL)

    while True:
        question = input("Ask: ").strip()
        if not question:
            continue
        if question == "q":
            break

        new_trace_id()

        initial_state: ChatBIState = {
            "question":          question,
            "resolved_question": "",
            "normalized_query":  "",
            "roles":             {},
            "schema_context":    {"tables": [], "join_paths": []},
            "generated_sql":     "",
            "final_sql":         "",
            "result":            [],
            "error":             "",
            "retries":           0,
            "redirect_hint":     "",
            "history":           history,
        }

        final_state = app.invoke(initial_state, config=config)

        # When a redirect hint exists, show it first and skip SQL/result output.
        if final_state.get("redirect_hint"):
            print(Fore.YELLOW + Style.BRIGHT + "[Please Rephrase]" + Style.RESET_ALL)
            print(Fore.YELLOW + final_state["redirect_hint"] + Style.RESET_ALL)
            print()
            continue

        resolved = final_state.get("resolved_question", "")
        if resolved and resolved != question:
            print(Fore.MAGENTA + f"[Resolved Question] {question} -> {resolved}" + Style.RESET_ALL)

        if final_state["normalized_query"] not in (question, resolved):
            print(Fore.YELLOW + f"[Normalized Query] -> {final_state['normalized_query']}" + Style.RESET_ALL)

        roles_text = format_roles(final_state.get("roles", {}))
        if roles_text:
            print(Fore.CYAN + f"[Intent Analysis]\n{roles_text}" + Style.RESET_ALL)

        display_sql = final_state.get("final_sql") or final_state.get("generated_sql", "")
        print(Fore.BLUE + f"[SQL]\n{display_sql}" + Style.RESET_ALL)

        if final_state.get("error"):
            print(Fore.RED + f"[Error] {final_state['error']}" + Style.RESET_ALL)
        else:
            row_count = len(final_state["result"])
            print(Fore.GREEN + f"[Result] {row_count} rows" + Style.RESET_ALL)
            for row in final_state["result"][:5]:
                print(f"  {row}")
            print(Style.DIM + "  If the result is not what you expected, just type a new description to query again." + Style.RESET_ALL)

            # Append successful turns to history.
            history.append({
                "question":       resolved if resolved and resolved != question else question,
                "roles":          final_state.get("roles", {}),
                "result_summary": f"returned {row_count} rows",
            })
            history = history[-5:]   # Keep only the 5 most recent turns.

        retries = final_state.get("retries", 0)
        if retries > 0:
            print(Fore.YELLOW + f"[SQL Checker] Retry count: {retries}" + Style.RESET_ALL)
        print()


if __name__ == "__main__":
    main()
